"""
scraper_api.py — Scraper usando Lyrics.ovh API
===============================================
API REST gratuita, sin API key, sin bloqueos de IP.
Endpoint: https://api.lyrics.ovh/v1/{artista}/{cancion}

Catalogo: 1,054 canciones en 10 generos.
Buenas practicas aplicadas:
  - time.sleep() con jitter entre requests
  - Manejo de errores HTTP (404, 429, timeout)
  - Deteccion de duplicados con corpus existente
"""

import time
import random
import logging
from typing import Optional

import requests
import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

API_BASE = "https://api.lyrics.ovh/v1"
HEADERS  = {
    "User-Agent": "Mozilla/5.0 (proyecto universitario CUC - mineria de textos)",
    "Accept": "application/json",
}


SONGS_BY_GENRE: dict[str, list[tuple[str, str]]] = {
    # Rock (115 canciones)
    "Rock": [
        ("Nirvana", "Smells Like Teen Spirit"),
        ("Nirvana", "Come as You Are"),
        ("Nirvana", "Lithium"),
        ("Nirvana", "In Bloom"),
        ("Nirvana", "Heart-Shaped Box"),
        ("Nirvana", "Rape Me"),
        ("Nirvana", "All Apologies"),
        ("Nirvana", "Polly"),
        ("Nirvana", "Drain You"),
        ("Nirvana", "Oh Well"),
        ("Radiohead", "Creep"),
        ("Radiohead", "Karma Police"),
        ("Radiohead", "Fake Plastic Trees"),
        ("Radiohead", "High and Dry"),
        ("Radiohead", "Street Spirit"),
        ("Radiohead", "No Surprises"),
        ("Radiohead", "Exit Music"),
        ("Radiohead", "Paranoid Android"),
        ("Radiohead", "Lucky"),
        ("Radiohead", "The Bends"),
        ("The Killers", "Mr Brightside"),
        ("The Killers", "Somebody Told Me"),
        ("The Killers", "Human"),
        ("The Killers", "When You Were Young"),
        ("The Killers", "Read My Mind"),
        ("The Killers", "Spaceman"),
        ("The Killers", "Runaways"),
        ("The Killers", "All These Things That I Have Done"),
        ("The Killers", "Smile Like You Mean It"),
        ("The Killers", "Miss Atomic Bomb"),
        ("Arctic Monkeys", "Do I Wanna Know"),
        ("Arctic Monkeys", "R U Mine"),
        ("Arctic Monkeys", "505"),
        ("Arctic Monkeys", "Fluorescent Adolescent"),
        ("Arctic Monkeys", "I Bet You Look Good on the Dancefloor"),
        ("Arctic Monkeys", "Snap Out of It"),
        ("Arctic Monkeys", "Knee Socks"),
        ("Arctic Monkeys", "Why'd You Only Call Me When You're High"),
        ("Arctic Monkeys", "One for the Road"),
        ("Arctic Monkeys", "Crying Lightning"),
        ("Foo Fighters", "Everlong"),
        ("Foo Fighters", "Best of You"),
        ("Foo Fighters", "Learn to Fly"),
        ("Foo Fighters", "The Pretender"),
        ("Foo Fighters", "Walk"),
        ("Foo Fighters", "Times Like These"),
        ("Foo Fighters", "All My Life"),
        ("Foo Fighters", "These Days"),
        ("Foo Fighters", "Long Road to Ruin"),
        ("Foo Fighters", "Rope"),
        ("Green Day", "Boulevard of Broken Dreams"),
        ("Green Day", "Wake Me Up When September Ends"),
        ("Green Day", "Good Riddance"),
        ("Green Day", "American Idiot"),
        ("Green Day", "21 Guns"),
        ("Green Day", "Holiday"),
        ("Green Day", "Know Your Enemy"),
        ("Green Day", "Basket Case"),
        ("Green Day", "Minority"),
        ("Green Day", "Brain Stew"),
        ("Linkin Park", "In the End"),
        ("Linkin Park", "Numb"),
        ("Linkin Park", "Crawling"),
        ("Linkin Park", "Breaking the Habit"),
        ("Linkin Park", "What I've Done"),
        ("Linkin Park", "Somewhere I Belong"),
        ("Linkin Park", "Faint"),
        ("Linkin Park", "New Divide"),
        ("Linkin Park", "Iridescent"),
        ("Linkin Park", "Shadow of the Day"),
        ("Pearl Jam", "Black"),
        ("Pearl Jam", "Alive"),
        ("Pearl Jam", "Better Man"),
        ("Pearl Jam", "Jeremy"),
        ("Pearl Jam", "Last Kiss"),
        ("Red Hot Chili Peppers", "Under the Bridge"),
        ("Red Hot Chili Peppers", "Californication"),
        ("Red Hot Chili Peppers", "Scar Tissue"),
        ("Red Hot Chili Peppers", "By the Way"),
        ("Red Hot Chili Peppers", "Soul to Squeeze"),
        ("U2", "With or Without You"),
        ("U2", "One"),
        ("U2", "Where the Streets Have No Name"),
        ("U2", "Beautiful Day"),
        ("U2", "Still Haven't Found What I'm Looking For"),
        ("Oasis", "Wonderwall"),
        ("Oasis", "Champagne Supernova"),
        ("Oasis", "Don't Look Back in Anger"),
        ("Oasis", "Half the World Away"),
        ("Oasis", "Whatever"),
        ("Coldplay", "The Scientist"),
        ("Coldplay", "Yellow"),
        ("Coldplay", "Fix You"),
        ("Coldplay", "Clocks"),
        ("Coldplay", "Speed of Sound"),
        ("Muse", "Supermassive Black Hole"),
        ("Muse", "Madness"),
        ("Muse", "Uprising"),
        ("Muse", "Starlight"),
        ("Muse", "Time Is Running Out"),
        ("Soundgarden", "Black Hole Sun"),
        ("Soundgarden", "Fell on Black Days"),
        ("Soundgarden", "Spoonman"),
        ("Alice in Chains", "Would"),
        ("Alice in Chains", "Rooster"),
        ("Alice in Chains", "Down in a Hole"),
        ("Audioslave", "Like a Stone"),
        ("Audioslave", "Show Me How to Live"),
        ("Audioslave", "Be Yourself"),
        ("Queens of the Stone Age", "No One Knows"),
        ("Queens of the Stone Age", "Go with the Flow"),
        ("Queens of the Stone Age", "Little Sister"),
        ("The Smashing Pumpkins", "Bullet with Butterfly Wings"),
        ("The Smashing Pumpkins", "Today"),
        ("The Smashing Pumpkins", "1979"),
    ],
    # Pop (110 canciones)
    "Pop": [
        ("Taylor Swift", "Love Story"),
        ("Taylor Swift", "Blank Space"),
        ("Taylor Swift", "Shake It Off"),
        ("Taylor Swift", "You Belong With Me"),
        ("Taylor Swift", "Bad Blood"),
        ("Taylor Swift", "Style"),
        ("Taylor Swift", "Wildest Dreams"),
        ("Taylor Swift", "Out of the Woods"),
        ("Taylor Swift", "Clean"),
        ("Taylor Swift", "All Too Well"),
        ("Taylor Swift", "We Are Never Getting Back Together"),
        ("Taylor Swift", "22"),
        ("Ed Sheeran", "Shape of You"),
        ("Ed Sheeran", "Thinking Out Loud"),
        ("Ed Sheeran", "Perfect"),
        ("Ed Sheeran", "Photograph"),
        ("Ed Sheeran", "Castle on the Hill"),
        ("Ed Sheeran", "Don't"),
        ("Ed Sheeran", "Bloodstream"),
        ("Ed Sheeran", "Lego House"),
        ("Ed Sheeran", "The A Team"),
        ("Ed Sheeran", "Give Me Love"),
        ("Ariana Grande", "Thank U Next"),
        ("Ariana Grande", "7 Rings"),
        ("Ariana Grande", "Problem"),
        ("Ariana Grande", "Break Free"),
        ("Ariana Grande", "Into You"),
        ("Ariana Grande", "No Tears Left to Cry"),
        ("Ariana Grande", "God Is a Woman"),
        ("Ariana Grande", "One Last Time"),
        ("Ariana Grande", "Side to Side"),
        ("Ariana Grande", "Dangerous Woman"),
        ("Billie Eilish", "Bad Guy"),
        ("Billie Eilish", "Ocean Eyes"),
        ("Billie Eilish", "Lovely"),
        ("Billie Eilish", "Bellyache"),
        ("Billie Eilish", "When the Party's Over"),
        ("Billie Eilish", "Bury a Friend"),
        ("Billie Eilish", "Wish You Were Gay"),
        ("Billie Eilish", "All the Good Girls Go to Hell"),
        ("Bruno Mars", "Just the Way You Are"),
        ("Bruno Mars", "Grenade"),
        ("Bruno Mars", "Locked Out of Heaven"),
        ("Bruno Mars", "Treasure"),
        ("Bruno Mars", "When I Was Your Man"),
        ("Bruno Mars", "The Lazy Song"),
        ("Bruno Mars", "Uptown Funk"),
        ("Bruno Mars", "Marry You"),
        ("Katy Perry", "Roar"),
        ("Katy Perry", "Firework"),
        ("Katy Perry", "Dark Horse"),
        ("Katy Perry", "Teenage Dream"),
        ("Katy Perry", "California Gurls"),
        ("Katy Perry", "Last Friday Night"),
        ("Katy Perry", "Part of Me"),
        ("Katy Perry", "Wide Awake"),
        ("Lady Gaga", "Poker Face"),
        ("Lady Gaga", "Bad Romance"),
        ("Lady Gaga", "Just Dance"),
        ("Lady Gaga", "Alejandro"),
        ("Lady Gaga", "Born This Way"),
        ("Lady Gaga", "Edge of Glory"),
        ("Lady Gaga", "Shallow"),
        ("Lady Gaga", "Million Reasons"),
        ("Justin Bieber", "Baby"),
        ("Justin Bieber", "Love Yourself"),
        ("Justin Bieber", "Sorry"),
        ("Justin Bieber", "What Do You Mean"),
        ("Justin Bieber", "Boyfriend"),
        ("Justin Bieber", "Stay"),
        ("Justin Bieber", "Peaches"),
        ("Dua Lipa", "Levitating"),
        ("Dua Lipa", "Don't Start Now"),
        ("Dua Lipa", "New Rules"),
        ("Dua Lipa", "Physical"),
        ("Dua Lipa", "Break My Heart"),
        ("Dua Lipa", "One Kiss"),
        ("Rihanna", "Umbrella"),
        ("Rihanna", "We Found Love"),
        ("Rihanna", "Stay"),
        ("Rihanna", "Diamonds"),
        ("Rihanna", "Only Girl"),
        ("Rihanna", "Love the Way You Lie"),
        ("Rihanna", "Take a Bow"),
        ("Adele", "Rolling in the Deep"),
        ("Adele", "Someone Like You"),
        ("Adele", "Hello"),
        ("Adele", "Set Fire to the Rain"),
        ("Adele", "Skyfall"),
        ("Adele", "Make You Feel My Love"),
        ("Adele", "Chasing Pavements"),
        ("Selena Gomez", "Come and Get It"),
        ("Selena Gomez", "Good for You"),
        ("Selena Gomez", "Wolves"),
        ("Selena Gomez", "Lose You to Love Me"),
        ("Miley Cyrus", "Wrecking Ball"),
        ("Miley Cyrus", "The Climb"),
        ("Miley Cyrus", "Midnight Sky"),
        ("Halsey", "Without Me"),
        ("Halsey", "Graveyard"),
        ("Halsey", "Colors"),
        ("Halsey", "Bad at Love"),
        ("Post Malone", "Circles"),
        ("Post Malone", "Sunflower"),
        ("Post Malone", "Rockstar"),
        ("Post Malone", "Better Now"),
        ("Shawn Mendes", "Stitches"),
        ("Shawn Mendes", "Treat You Better"),
        ("Shawn Mendes", "There's Nothing Holdin' Me Back"),
        ("Shawn Mendes", "In My Blood"),
    ],
    # Hip-Hop (114 canciones)
    "Hip-Hop": [
        ("Eminem", "Lose Yourself"),
        ("Eminem", "Not Afraid"),
        ("Eminem", "The Real Slim Shady"),
        ("Eminem", "Without Me"),
        ("Eminem", "Rap God"),
        ("Eminem", "Stan"),
        ("Eminem", "Beautiful"),
        ("Eminem", "Mockingbird"),
        ("Eminem", "When I'm Gone"),
        ("Eminem", "Cleanin Out My Closet"),
        ("Eminem", "Love the Way You Lie"),
        ("Eminem", "River"),
        ("Kendrick Lamar", "HUMBLE"),
        ("Kendrick Lamar", "DNA"),
        ("Kendrick Lamar", "Alright"),
        ("Kendrick Lamar", "Swimming Pools"),
        ("Kendrick Lamar", "Money Trees"),
        ("Kendrick Lamar", "Poetic Justice"),
        ("Kendrick Lamar", "Backseat Freestyle"),
        ("Kendrick Lamar", "King Kunta"),
        ("Kendrick Lamar", "Bitch Don't Kill My Vibe"),
        ("Kendrick Lamar", "m.A.A.d city"),
        ("Drake", "Hotline Bling"),
        ("Drake", "God's Plan"),
        ("Drake", "One Dance"),
        ("Drake", "Started From the Bottom"),
        ("Drake", "Hold On We're Going Home"),
        ("Drake", "Take Care"),
        ("Drake", "Marvins Room"),
        ("Drake", "Best I Ever Had"),
        ("Drake", "Passionfruit"),
        ("Drake", "In My Feelings"),
        ("Kanye West", "Gold Digger"),
        ("Kanye West", "Stronger"),
        ("Kanye West", "All Falls Down"),
        ("Kanye West", "Runaway"),
        ("Kanye West", "Jesus Walks"),
        ("Kanye West", "Heartless"),
        ("Kanye West", "Power"),
        ("Jay-Z", "Empire State of Mind"),
        ("Jay-Z", "99 Problems"),
        ("Jay-Z", "Hard Knock Life"),
        ("Jay-Z", "Run This Town"),
        ("Lil Wayne", "A Milli"),
        ("Lil Wayne", "Lollipop"),
        ("Lil Wayne", "How to Love"),
        ("Lil Wayne", "6 Foot 7 Foot"),
        ("Macklemore", "Thrift Shop"),
        ("Macklemore", "Can't Hold Us"),
        ("Macklemore", "Same Love"),
        ("Macklemore", "Downtown"),
        ("Childish Gambino", "Redbone"),
        ("Childish Gambino", "This Is America"),
        ("Childish Gambino", "3005"),
        ("Childish Gambino", "Sweatpants"),
        ("J. Cole", "No Role Modelz"),
        ("J. Cole", "Love Yourz"),
        ("J. Cole", "Crooked Smile"),
        ("J. Cole", "Work Out"),
        ("Nicki Minaj", "Super Bass"),
        ("Nicki Minaj", "Anaconda"),
        ("Nicki Minaj", "Starships"),
        ("Nicki Minaj", "Bang Bang"),
        ("Cardi B", "Bodak Yellow"),
        ("Cardi B", "I Like It"),
        ("Cardi B", "WAP"),
        ("Cardi B", "Money"),
        ("Travis Scott", "Goosebumps"),
        ("Travis Scott", "Sicko Mode"),
        ("Travis Scott", "Antidote"),
        ("Travis Scott", "Butterfly Effect"),
        ("Migos", "Bad and Boujee"),
        ("Migos", "Walk It Talk It"),
        ("Migos", "Motorsport"),
        ("21 Savage", "Rockstar"),
        ("21 Savage", "Bank Account"),
        ("Future", "Mask Off"),
        ("Future", "Low Life"),
        ("Future", "March Madness"),
        ("Lil Uzi Vert", "XO Tour Llif3"),
        ("Lil Uzi Vert", "The Way Life Goes"),
        ("Logic", "1-800-273-8255"),
        ("Logic", "Nikki"),
        ("Logic", "Under Pressure"),
        ("Big Sean", "I Don't Fuck with You"),
        ("Big Sean", "One Man Can Change the World"),
        ("Chance the Rapper", "Blessings"),
        ("Chance the Rapper", "No Problem"),
        ("Chance the Rapper", "Same Drugs"),
        ("Wiz Khalifa", "Black and Yellow"),
        ("Wiz Khalifa", "See You Again"),
        ("Wiz Khalifa", "Work Hard Play Hard"),
        ("Snoop Dogg", "Drop It Like It's Hot"),
        ("Snoop Dogg", "Beautiful"),
        ("Ice Cube", "It Was a Good Day"),
        ("Ice Cube", "Check Yo Self"),
        ("A$AP Rocky", "Praise the Lord"),
        ("A$AP Rocky", "Everyday"),
        ("A$AP Rocky", "L$D"),
        ("Meek Mill", "Dreams and Nightmares"),
        ("Meek Mill", "Cold Hearted II"),
        ("Lil Baby", "Emotionally Scarred"),
        ("Lil Baby", "The Bigger Picture"),
        ("Lil Baby", "Grace"),
        ("Roddy Ricch", "The Box"),
        ("Roddy Ricch", "High Fashion"),
        ("Roddy Ricch", "Start wit Me"),
        ("DaBaby", "ROCKSTAR"),
        ("DaBaby", "Bop"),
        ("DaBaby", "Suge"),
        ("NF", "The Search"),
        ("NF", "Leave Me Alone"),
        ("NF", "Let You Down"),
        ("NF", "Mansion"),
    ],
    # Metal (109 canciones)
    "Metal": [
        ("Metallica", "Enter Sandman"),
        ("Metallica", "Nothing Else Matters"),
        ("Metallica", "One"),
        ("Metallica", "Master of Puppets"),
        ("Metallica", "The Unforgiven"),
        ("Metallica", "Fade to Black"),
        ("Metallica", "Sad but True"),
        ("Metallica", "Battery"),
        ("Metallica", "Wherever I May Roam"),
        ("Metallica", "The Day That Never Comes"),
        ("Iron Maiden", "The Trooper"),
        ("Iron Maiden", "Run to the Hills"),
        ("Iron Maiden", "Fear of the Dark"),
        ("Iron Maiden", "Hallowed Be Thy Name"),
        ("Iron Maiden", "Aces High"),
        ("Iron Maiden", "Number of the Beast"),
        ("Iron Maiden", "Wasted Years"),
        ("Iron Maiden", "The Clairvoyant"),
        ("Slipknot", "Psychosocial"),
        ("Slipknot", "Duality"),
        ("Slipknot", "Before I Forget"),
        ("Slipknot", "Wait and Bleed"),
        ("Slipknot", "The Devil in I"),
        ("Slipknot", "Vermilion"),
        ("Slipknot", "Snuff"),
        ("Slipknot", "Dead Memories"),
        ("System of a Down", "Chop Suey"),
        ("System of a Down", "Toxicity"),
        ("System of a Down", "B.Y.O.B."),
        ("System of a Down", "Aerials"),
        ("System of a Down", "Lonely Day"),
        ("System of a Down", "Hypnotize"),
        ("System of a Down", "Soldier Side"),
        ("Black Sabbath", "Iron Man"),
        ("Black Sabbath", "Paranoid"),
        ("Black Sabbath", "War Pigs"),
        ("Black Sabbath", "Children of the Grave"),
        ("Black Sabbath", "Sabbath Bloody Sabbath"),
        ("Pantera", "Walk"),
        ("Pantera", "Cowboys from Hell"),
        ("Pantera", "Cemetery Gates"),
        ("Pantera", "Floods"),
        ("Pantera", "This Love"),
        ("Avenged Sevenfold", "Nightmare"),
        ("Avenged Sevenfold", "Bat Country"),
        ("Avenged Sevenfold", "So Far Away"),
        ("Avenged Sevenfold", "Afterlife"),
        ("Avenged Sevenfold", "Hail to the King"),
        ("Avenged Sevenfold", "Coming Home"),
        ("Disturbed", "Down with the Sickness"),
        ("Disturbed", "The Sound of Silence"),
        ("Disturbed", "Stricken"),
        ("Disturbed", "Inside the Fire"),
        ("Disturbed", "Land of Confusion"),
        ("Bullet for My Valentine", "Tears Don't Fall"),
        ("Bullet for My Valentine", "Waking the Demon"),
        ("Bullet for My Valentine", "All These Things I Hate"),
        ("Bullet for My Valentine", "Hand of Blood"),
        ("Lamb of God", "Laid to Rest"),
        ("Lamb of God", "Redneck"),
        ("Lamb of God", "Walk with Me in Hell"),
        ("Tool", "Sober"),
        ("Tool", "Stinkfist"),
        ("Tool", "Schism"),
        ("Tool", "Parabola"),
        ("Tool", "Vicarious"),
        ("Ozzy Osbourne", "Crazy Train"),
        ("Ozzy Osbourne", "Mr Crowley"),
        ("Ozzy Osbourne", "No More Tears"),
        ("Ozzy Osbourne", "Mama I'm Coming Home"),
        ("Judas Priest", "Breaking the Law"),
        ("Judas Priest", "Living After Midnight"),
        ("Judas Priest", "You've Got Another Thing Coming"),
        ("Megadeth", "Symphony of Destruction"),
        ("Megadeth", "Peace Sells"),
        ("Megadeth", "Holy Wars"),
        ("Korn", "Freak on a Leash"),
        ("Korn", "Coming Undone"),
        ("Korn", "Did My Time"),
        ("Marilyn Manson", "The Beautiful People"),
        ("Marilyn Manson", "Sweet Dreams"),
        ("Marilyn Manson", "This Is the New Shit"),
        ("Five Finger Death Punch", "Wrong Side of Heaven"),
        ("Five Finger Death Punch", "Bad Company"),
        ("Five Finger Death Punch", "Far from Home"),
        ("Evanescence", "Bring Me to Life"),
        ("Evanescence", "My Immortal"),
        ("Evanescence", "Going Under"),
        ("Evanescence", "Lithium"),
        ("Nickelback", "How You Remind Me"),
        ("Nickelback", "Photograph"),
        ("Nickelback", "Rockstar"),
        ("Nickelback", "Far Away"),
        ("Seether", "Broken"),
        ("Seether", "Fake It"),
        ("Seether", "Remedy"),
        ("Breaking Benjamin", "The Diary of Jane"),
        ("Breaking Benjamin", "I Will Not Bow"),
        ("Breaking Benjamin", "Breath"),
        ("Shinedown", "Second Chance"),
        ("Shinedown", "Simple Man"),
        ("Shinedown", "45"),
        ("Three Days Grace", "Animal I Have Become"),
        ("Three Days Grace", "I Hate Everything About You"),
        ("Three Days Grace", "Pain"),
        ("Godsmack", "I Stand Alone"),
        ("Godsmack", "Awake"),
        ("Trivium", "In Waves"),
        ("Trivium", "Down from the Sky"),
    ],
    # Indie (113 canciones)
    "Indie": [
        ("Tame Impala", "Let It Happen"),
        ("Tame Impala", "The Less I Know the Better"),
        ("Tame Impala", "Feels Like We Only Go Backwards"),
        ("Tame Impala", "Eventually"),
        ("Tame Impala", "Elephant"),
        ("Tame Impala", "Yes I'm Changing"),
        ("Tame Impala", "New Person Same Old Mistakes"),
        ("Tame Impala", "Cause I'm a Man"),
        ("Tame Impala", "Why Won't You Make Up Your Mind"),
        ("Tame Impala", "Alter Ego"),
        ("The Strokes", "Last Nite"),
        ("The Strokes", "Reptilia"),
        ("The Strokes", "Someday"),
        ("The Strokes", "Hard to Explain"),
        ("The Strokes", "Juicebox"),
        ("The Strokes", "12:51"),
        ("The Strokes", "Heart in a Cage"),
        ("The Strokes", "Under Control"),
        ("Arcade Fire", "Wake Up"),
        ("Arcade Fire", "Rebellion"),
        ("Arcade Fire", "The Suburbs"),
        ("Arcade Fire", "Ready to Start"),
        ("Arcade Fire", "Sprawl II"),
        ("Arcade Fire", "We Used to Wait"),
        ("Vampire Weekend", "A-Punk"),
        ("Vampire Weekend", "Oxford Comma"),
        ("Vampire Weekend", "Cousins"),
        ("Vampire Weekend", "Cape Cod Kwassa Kwassa"),
        ("Vampire Weekend", "Unbelievers"),
        ("Vampire Weekend", "Hannah Hunt"),
        ("Florence and the Machine", "Dog Days Are Over"),
        ("Florence and the Machine", "Shake It Out"),
        ("Florence and the Machine", "You've Got the Love"),
        ("Florence and the Machine", "Cosmic Love"),
        ("Florence and the Machine", "Spectrum"),
        ("Florence and the Machine", "Drumming Song"),
        ("The 1975", "Chocolate"),
        ("The 1975", "Sex"),
        ("The 1975", "The Sound"),
        ("The 1975", "Robbers"),
        ("The 1975", "Girls"),
        ("The 1975", "Change of Heart"),
        ("The 1975", "Love Me"),
        ("Bon Iver", "Skinny Love"),
        ("Bon Iver", "Holocene"),
        ("Bon Iver", "Towers"),
        ("Bon Iver", "Blindsided"),
        ("Bon Iver", "re: Stacks"),
        ("Alt-J", "Something Good"),
        ("Alt-J", "Breezeblocks"),
        ("Alt-J", "Tessellate"),
        ("Alt-J", "Fitzpleasure"),
        ("Alt-J", "Matilda"),
        ("Beach House", "Space Song"),
        ("Beach House", "Myth"),
        ("Beach House", "Take Care"),
        ("Beach House", "Lazuli"),
        ("Hozier", "Take Me to Church"),
        ("Hozier", "Someone New"),
        ("Hozier", "Work Song"),
        ("Hozier", "From Eden"),
        ("Hozier", "Like Real People Do"),
        ("Lana Del Rey", "Video Games"),
        ("Lana Del Rey", "Young and Beautiful"),
        ("Lana Del Rey", "Summertime Sadness"),
        ("Lana Del Rey", "Blue Jeans"),
        ("Lana Del Rey", "Born to Die"),
        ("Lana Del Rey", "Ride"),
        ("Lana Del Rey", "West Coast"),
        ("Lana Del Rey", "Ultraviolence"),
        ("Phoebe Bridgers", "Funeral"),
        ("Phoebe Bridgers", "Savior Complex"),
        ("Phoebe Bridgers", "Garden Song"),
        ("Phoebe Bridgers", "Motion Sickness"),
        ("Mitski", "Your Best American Girl"),
        ("Mitski", "Nobody"),
        ("Mitski", "Washing Machine Heart"),
        ("Mitski", "First Love Late Spring"),
        ("Foals", "Mountain at My Gates"),
        ("Foals", "My Number"),
        ("Foals", "Spanish Sahara"),
        ("The War on Drugs", "Red Eyes"),
        ("The War on Drugs", "Under the Pressure"),
        ("The War on Drugs", "Pain"),
        ("Sufjan Stevens", "Death with Dignity"),
        ("Sufjan Stevens", "Chicago"),
        ("Sufjan Stevens", "Fourth of July"),
        ("Clairo", "Pretty Girl"),
        ("Clairo", "Sofia"),
        ("Clairo", "Bags"),
        ("Clairo", "Amoeba"),
        ("Rex Orange County", "Loving Is Easy"),
        ("Rex Orange County", "Sunflower"),
        ("Cigarettes After Sex", "K."),
        ("Cigarettes After Sex", "Affection"),
        ("Cigarettes After Sex", "Nothing's Gonna Hurt You Baby"),
        ("Weyes Blood", "Andromeda"),
        ("Weyes Blood", "Everyday"),
        ("Japanese Breakfast", "Everybody Wants to Love You"),
        ("Japanese Breakfast", "Boyish"),
        ("Car Seat Headrest", "Fill in the Blank"),
        ("Car Seat Headrest", "Drunk Drivers Killer Whales"),
        ("Snail Mail", "Pristine"),
        ("Snail Mail", "Heat Wave"),
        ("Soccer Mommy", "Circle the Drain"),
        ("Soccer Mommy", "Still Clean"),
        ("Men I Trust", "Tailwhip"),
        ("Men I Trust", "Show Me How"),
        ("King Krule", "Dum Surfer"),
        ("King Krule", "Easy Easy"),
        ("Real Estate", "Crime"),
        ("Real Estate", "Easy"),
        ("Real Estate", "Talking Backwards"),
    ],
    # Country (99 canciones)
    "Country": [
        ("Johnny Cash", "Ring of Fire"),
        ("Johnny Cash", "Hurt"),
        ("Johnny Cash", "Man in Black"),
        ("Johnny Cash", "Folsom Prison Blues"),
        ("Johnny Cash", "Walk the Line"),
        ("Johnny Cash", "Jackson"),
        ("Johnny Cash", "Sunday Mornin Coming Down"),
        ("Johnny Cash", "Get Rhythm"),
        ("Dolly Parton", "Jolene"),
        ("Dolly Parton", "I Will Always Love You"),
        ("Dolly Parton", "9 to 5"),
        ("Dolly Parton", "Coat of Many Colors"),
        ("Dolly Parton", "Islands in the Stream"),
        ("Luke Bryan", "Country Girl"),
        ("Luke Bryan", "Play It Again"),
        ("Luke Bryan", "Crash My Party"),
        ("Luke Bryan", "That's My Kind of Night"),
        ("Luke Bryan", "Drink a Beer"),
        ("Blake Shelton", "God's Country"),
        ("Blake Shelton", "Austin"),
        ("Blake Shelton", "Sangria"),
        ("Blake Shelton", "Boys Round Here"),
        ("Kenny Rogers", "The Gambler"),
        ("Kenny Rogers", "Lucille"),
        ("Kenny Rogers", "Lady"),
        ("Carrie Underwood", "Before He Cheats"),
        ("Carrie Underwood", "Jesus Take the Wheel"),
        ("Carrie Underwood", "Blown Away"),
        ("Carrie Underwood", "Undo It"),
        ("Carrie Underwood", "See You Again"),
        ("Keith Urban", "Blue Ain't Your Color"),
        ("Keith Urban", "Somebody Like You"),
        ("Keith Urban", "Long Hot Summer"),
        ("Brad Paisley", "Then"),
        ("Brad Paisley", "She's Everything"),
        ("Brad Paisley", "This Is Country Music"),
        ("Brad Paisley", "Mud on the Tires"),
        ("Tim McGraw", "Live Like You Were Dying"),
        ("Tim McGraw", "Something Like That"),
        ("Tim McGraw", "Humble and Kind"),
        ("Tim McGraw", "My Best Friend"),
        ("Rascal Flatts", "Bless the Broken Road"),
        ("Rascal Flatts", "What Hurts the Most"),
        ("Rascal Flatts", "Life Is a Highway"),
        ("Rascal Flatts", "My Wish"),
        ("Zac Brown Band", "Chicken Fried"),
        ("Zac Brown Band", "Colder Weather"),
        ("Zac Brown Band", "Toes"),
        ("Zac Brown Band", "Free"),
        ("Miranda Lambert", "The House That Built Me"),
        ("Miranda Lambert", "Gunpowder and Lead"),
        ("Miranda Lambert", "Mama's Broken Heart"),
        ("Miranda Lambert", "White Liar"),
        ("Florida Georgia Line", "Cruise"),
        ("Florida Georgia Line", "This Is How We Roll"),
        ("Florida Georgia Line", "H.O.L.Y."),
        ("Chris Stapleton", "Tennessee Whiskey"),
        ("Chris Stapleton", "Traveller"),
        ("Chris Stapleton", "Broken Halos"),
        ("Chris Stapleton", "Parachute"),
        ("Kacey Musgraves", "Rainbow"),
        ("Kacey Musgraves", "Butterflies"),
        ("Kacey Musgraves", "Slow Burn"),
        ("Kacey Musgraves", "Space Cowboy"),
        ("Sam Hunt", "Body Like a Back Road"),
        ("Sam Hunt", "Take Your Time"),
        ("Sam Hunt", "Break Up in a Small Town"),
        ("Dierks Bentley", "Drunk on a Plane"),
        ("Dierks Bentley", "What Was I Thinkin"),
        ("Thomas Rhett", "Die a Happy Man"),
        ("Thomas Rhett", "Unforgettable"),
        ("Thomas Rhett", "Craving You"),
        ("Jason Aldean", "Dirt Road Anthem"),
        ("Jason Aldean", "She's Country"),
        ("Jason Aldean", "Fly Over States"),
        ("Kenny Chesney", "There Goes My Life"),
        ("Kenny Chesney", "Beer in Mexico"),
        ("Kenny Chesney", "American Kids"),
        ("Luke Combs", "Beautiful Crazy"),
        ("Luke Combs", "Beer Never Broke My Heart"),
        ("Luke Combs", "When It Rains It Pours"),
        ("Morgan Wallen", "Whiskey Glasses"),
        ("Morgan Wallen", "7 Summers"),
        ("Morgan Wallen", "Wasted on You"),
        ("Eric Church", "Drink in My Hand"),
        ("Eric Church", "Record Year"),
        ("Eric Church", "Springsteen"),
        ("Maren Morris", "My Church"),
        ("Maren Morris", "The Bones"),
        ("Maren Morris", "Girl"),
        ("Tyler Childers", "Whitehouse Road"),
        ("Tyler Childers", "Feathered Indians"),
        ("Tyler Childers", "House Fire"),
        ("Sturgill Simpson", "Turtles All the Way Down"),
        ("Sturgill Simpson", "Life of Sin"),
        ("Colter Wall", "Codeine Dream"),
        ("Colter Wall", "Sleeping on the Blacktop"),
        ("Cody Johnson", "On My Way to You"),
        ("Cody Johnson", "With You I Am"),
    ],
    # Jazz (87 canciones)
    "Jazz": [
        ("Frank Sinatra", "My Way"),
        ("Frank Sinatra", "New York New York"),
        ("Frank Sinatra", "Fly Me to the Moon"),
        ("Frank Sinatra", "The Way You Look Tonight"),
        ("Frank Sinatra", "Summer Wind"),
        ("Frank Sinatra", "That's Life"),
        ("Frank Sinatra", "Strangers in the Night"),
        ("Frank Sinatra", "Come Fly with Me"),
        ("Frank Sinatra", "I've Got You Under My Skin"),
        ("Frank Sinatra", "The Best Is Yet to Come"),
        ("Ella Fitzgerald", "Summertime"),
        ("Ella Fitzgerald", "Blue Skies"),
        ("Ella Fitzgerald", "Misty"),
        ("Ella Fitzgerald", "Bewitched"),
        ("Amy Winehouse", "Back to Black"),
        ("Amy Winehouse", "Rehab"),
        ("Amy Winehouse", "Valerie"),
        ("Amy Winehouse", "Tears Dry on Their Own"),
        ("Amy Winehouse", "Stronger Than Me"),
        ("Amy Winehouse", "You Know I'm No Good"),
        ("Amy Winehouse", "Love Is a Losing Game"),
        ("Amy Winehouse", "Addicted"),
        ("Norah Jones", "Come Away with Me"),
        ("Norah Jones", "Don't Know Why"),
        ("Norah Jones", "Turn Me On"),
        ("Norah Jones", "Sunrise"),
        ("Norah Jones", "Feelin the Same Way"),
        ("Michael Buble", "Haven't Met You Yet"),
        ("Michael Buble", "Feeling Good"),
        ("Michael Buble", "Cry Me a River"),
        ("Michael Buble", "Everything"),
        ("Michael Buble", "Moondance"),
        ("Michael Buble", "Sway"),
        ("Diana Krall", "The Look of Love"),
        ("Diana Krall", "Fly Me to the Moon"),
        ("Diana Krall", "Let's Fall in Love"),
        ("Tony Bennett", "I Left My Heart in San Francisco"),
        ("Tony Bennett", "The Best Is Yet to Come"),
        ("Tony Bennett", "Because of You"),
        ("Billie Holiday", "God Bless the Child"),
        ("Billie Holiday", "Strange Fruit"),
        ("Billie Holiday", "Summertime"),
        ("Billie Holiday", "All of Me"),
        ("Nat King Cole", "Unforgettable"),
        ("Nat King Cole", "L-O-V-E"),
        ("Nat King Cole", "Nature Boy"),
        ("Nat King Cole", "Mona Lisa"),
        ("Dean Martin", "That's Amore"),
        ("Dean Martin", "Everybody Loves Somebody"),
        ("Dean Martin", "Volare"),
        ("Dean Martin", "Sway"),
        ("Etta James", "At Last"),
        ("Etta James", "Something's Got a Hold on Me"),
        ("Etta James", "I'd Rather Go Blind"),
        ("Etta James", "Sunday Kind of Love"),
        ("Louis Armstrong", "What a Wonderful World"),
        ("Louis Armstrong", "La Vie En Rose"),
        ("Louis Armstrong", "When the Saints Go Marching In"),
        ("Nina Simone", "Feeling Good"),
        ("Nina Simone", "I Put a Spell on You"),
        ("Nina Simone", "Sinnerman"),
        ("Nina Simone", "My Baby Just Cares for Me"),
        ("Chet Baker", "Almost Blue"),
        ("Chet Baker", "My Funny Valentine"),
        ("Chet Baker", "There Will Never Be Another You"),
        ("Astrud Gilberto", "The Girl from Ipanema"),
        ("Astrud Gilberto", "Agua de Beber"),
        ("Bobby Darin", "Beyond the Sea"),
        ("Bobby Darin", "Mack the Knife"),
        ("Sammy Davis Jr", "The Candy Man"),
        ("Sammy Davis Jr", "Mr Bojangles"),
        ("Dinah Washington", "What a Difference a Day Makes"),
        ("Dinah Washington", "Unforgettable"),
        ("Peggy Lee", "Fever"),
        ("Peggy Lee", "Is That All There Is"),
        ("Shirley Bassey", "Goldfinger"),
        ("Shirley Bassey", "Big Spender"),
        ("Sarah Vaughan", "Misty"),
        ("Sarah Vaughan", "Lullaby of Birdland"),
        ("Carmen McRae", "Round Midnight"),
        ("Mel Torme", "The Christmas Song"),
        ("Lena Horne", "Stormy Weather"),
        ("Lena Horne", "The Lady Is a Tramp"),
        ("Rosemary Clooney", "Come On-a My House"),
        ("Rosemary Clooney", "Mambo Italiano"),
        ("Johnny Hartman", "Lush Life"),
        ("Johnny Hartman", "They Say It's Wonderful"),
    ],
    # Electronic (102 canciones)
    "Electronic": [
        ("Daft Punk", "Get Lucky"),
        ("Daft Punk", "Around the World"),
        ("Daft Punk", "One More Time"),
        ("Daft Punk", "Harder Better Faster Stronger"),
        ("Daft Punk", "Instant Crush"),
        ("Daft Punk", "Lose Yourself to Dance"),
        ("Daft Punk", "Within"),
        ("Daft Punk", "Give Life Back to Music"),
        ("The Chainsmokers", "Roses"),
        ("The Chainsmokers", "Closer"),
        ("The Chainsmokers", "Something Just Like This"),
        ("The Chainsmokers", "Don't Let Me Down"),
        ("The Chainsmokers", "Paris"),
        ("The Chainsmokers", "Young"),
        ("Avicii", "Wake Me Up"),
        ("Avicii", "Hey Brother"),
        ("Avicii", "Without You"),
        ("Avicii", "Addicted to You"),
        ("Avicii", "Waiting for Love"),
        ("Avicii", "The Days"),
        ("Calvin Harris", "Feel So Close"),
        ("Calvin Harris", "Summer"),
        ("Calvin Harris", "This Is What You Came For"),
        ("Calvin Harris", "My Way"),
        ("Calvin Harris", "Slide"),
        ("Calvin Harris", "Rollin"),
        ("David Guetta", "Titanium"),
        ("David Guetta", "Without You"),
        ("David Guetta", "She Wolf"),
        ("David Guetta", "Hey Mama"),
        ("David Guetta", "Dangerous"),
        ("Marshmello", "Alone"),
        ("Marshmello", "Happier"),
        ("Marshmello", "Friends"),
        ("Marshmello", "Wolves"),
        ("Kygo", "Firestone"),
        ("Kygo", "Stay"),
        ("Kygo", "It Ain't Me"),
        ("Kygo", "Stole the Show"),
        ("Zedd", "Clarity"),
        ("Zedd", "Beautiful Now"),
        ("Zedd", "Stay the Night"),
        ("Zedd", "The Middle"),
        ("Martin Garrix", "Animals"),
        ("Martin Garrix", "In the Name of Love"),
        ("Martin Garrix", "Scared to Be Lonely"),
        ("Tiesto", "Red Lights"),
        ("Tiesto", "The Business"),
        ("Tiesto", "Wasted"),
        ("Tiesto", "Boom"),
        ("Skrillex", "Bangarang"),
        ("Skrillex", "First of the Year"),
        ("Skrillex", "Scary Monsters and Nice Sprites"),
        ("Major Lazer", "Lean On"),
        ("Major Lazer", "Cold Water"),
        ("Major Lazer", "Light It Up"),
        ("Disclosure", "Latch"),
        ("Disclosure", "You and Me"),
        ("Disclosure", "Holding On"),
        ("Clean Bandit", "Rather Be"),
        ("Clean Bandit", "Rockabye"),
        ("Clean Bandit", "Stronger"),
        ("Flume", "Never Be Like You"),
        ("Flume", "Say It"),
        ("Flume", "Drop the Game"),
        ("Porter Robinson", "Language"),
        ("Porter Robinson", "Shelter"),
        ("Odesza", "Say My Name"),
        ("Odesza", "Line of Sight"),
        ("Bonobo", "Kerala"),
        ("Bonobo", "Kiara"),
        ("Bonobo", "No Reason"),
        ("Moby", "Porcelain"),
        ("Moby", "Natural Blues"),
        ("Moby", "Why Does My Heart Feel So Bad"),
        ("The Chemical Brothers", "Block Rockin Beats"),
        ("The Chemical Brothers", "Setting Sun"),
        ("The Chemical Brothers", "Galvanize"),
        ("Prodigy", "Firestarter"),
        ("Prodigy", "Breathe"),
        ("Deadmau5", "I Remember"),
        ("Deadmau5", "Ghosts N Stuff"),
        ("Diplo", "Revolution"),
        ("Diplo", "Be Right There"),
        ("Alesso", "Heroes"),
        ("Alesso", "Cool"),
        ("Alesso", "Take My Breath Away"),
        ("ILLENIUM", "Needed You"),
        ("ILLENIUM", "Crawl Outta Love"),
        ("ILLENIUM", "Feel Good"),
        ("Gryffin", "Heading Home"),
        ("Gryffin", "Tie Me Down"),
        ("San Holo", "Light"),
        ("San Holo", "lift me from the ground"),
        ("Petit Biscuit", "Sunset Lover"),
        ("Petit Biscuit", "Problems"),
        ("Louis The Child", "It's Strange"),
        ("Louis The Child", "Better Not"),
        ("blackbear", "do re mi"),
        ("blackbear", "hot girl bummer"),
        ("Knife Party", "Internet Friends"),
        ("Knife Party", "Bonfire"),
    ],
    # R&B (101 canciones)
    "R&B": [
        ("Beyonce", "Halo"),
        ("Beyonce", "Crazy in Love"),
        ("Beyonce", "Single Ladies"),
        ("Beyonce", "Irreplaceable"),
        ("Beyonce", "Love On Top"),
        ("Beyonce", "Drunk in Love"),
        ("Beyonce", "Formation"),
        ("Beyonce", "Haunted"),
        ("Frank Ocean", "Thinking Bout You"),
        ("Frank Ocean", "Pyramids"),
        ("Frank Ocean", "Bad Religion"),
        ("Frank Ocean", "Pink Matter"),
        ("Frank Ocean", "Lost"),
        ("The Weeknd", "Blinding Lights"),
        ("The Weeknd", "Can't Feel My Face"),
        ("The Weeknd", "Starboy"),
        ("The Weeknd", "The Hills"),
        ("The Weeknd", "Save Your Tears"),
        ("The Weeknd", "Call Out My Name"),
        ("The Weeknd", "Earned It"),
        ("The Weeknd", "Often"),
        ("The Weeknd", "I Feel It Coming"),
        ("Usher", "Yeah"),
        ("Usher", "Confessions Part II"),
        ("Usher", "My Boo"),
        ("Usher", "Burn"),
        ("Usher", "OMG"),
        ("Alicia Keys", "No One"),
        ("Alicia Keys", "If I Ain't Got You"),
        ("Alicia Keys", "Fallin"),
        ("Alicia Keys", "Girl on Fire"),
        ("Alicia Keys", "Empire State of Mind"),
        ("John Legend", "All of Me"),
        ("John Legend", "Ordinary People"),
        ("John Legend", "Save Room"),
        ("John Legend", "Tonight"),
        ("Mary J Blige", "No More Drama"),
        ("Mary J Blige", "Be Without You"),
        ("Mary J Blige", "Family Affair"),
        ("Ne-Yo", "So Sick"),
        ("Ne-Yo", "Closer"),
        ("Ne-Yo", "Miss Independent"),
        ("Ne-Yo", "Because of You"),
        ("Chris Brown", "With You"),
        ("Chris Brown", "Forever"),
        ("Chris Brown", "No Guidance"),
        ("H.E.R.", "Best Part"),
        ("H.E.R.", "Focus"),
        ("H.E.R.", "Fate"),
        ("SZA", "Love Galore"),
        ("SZA", "The Weekend"),
        ("SZA", "Good Days"),
        ("SZA", "Broken Clocks"),
        ("Khalid", "Location"),
        ("Khalid", "Young Dumb Broke"),
        ("Khalid", "Better"),
        ("Khalid", "Talk"),
        ("Daniel Caesar", "Get You"),
        ("Daniel Caesar", "Best Part"),
        ("Daniel Caesar", "Blessed"),
        ("Jhene Aiko", "Comfort Inn"),
        ("Jhene Aiko", "Spotless Mind"),
        ("Jhene Aiko", "Bed Peace"),
        ("Anderson Paak", "Come Down"),
        ("Anderson Paak", "Make It Better"),
        ("Anderson Paak", "Am I Wrong"),
        ("Giveon", "Heartbreak Anniversary"),
        ("Giveon", "Vanish"),
        ("Summer Walker", "Girls Need Love"),
        ("Summer Walker", "Playing Games"),
        ("Kehlani", "Gangsta"),
        ("Kehlani", "Nights Like This"),
        ("Kehlani", "Honey"),
        ("Mariah Carey", "Always Be My Baby"),
        ("Mariah Carey", "Hero"),
        ("Mariah Carey", "We Belong Together"),
        ("Mariah Carey", "Emotions"),
        ("Whitney Houston", "I Will Always Love You"),
        ("Whitney Houston", "Greatest Love of All"),
        ("Whitney Houston", "I Wanna Dance with Somebody"),
        ("Toni Braxton", "Un-Break My Heart"),
        ("Toni Braxton", "He Wasn't Man Enough"),
        ("Brandy", "Have You Ever"),
        ("Brandy", "I Wanna Be Down"),
        ("Monica", "Before You Walk Out of My Life"),
        ("Monica", "The First Night"),
        ("Destiny's Child", "Say My Name"),
        ("Destiny's Child", "Survivor"),
        ("Destiny's Child", "Bootylicious"),
        ("Maxwell", "Ascension"),
        ("Maxwell", "Fortunate"),
        ("D'Angelo", "Brown Sugar"),
        ("D'Angelo", "Untitled How Does It Feel"),
        ("Erykah Badu", "On and On"),
        ("Erykah Badu", "Bag Lady"),
        ("Erykah Badu", "Didn't Cha Know"),
        ("Lauryn Hill", "Ex-Factor"),
        ("Lauryn Hill", "Doo Wop"),
        ("Lauryn Hill", "Everything Is Everything"),
        ("Lil Baby", "Emotionally Scarred"),
        ("Lucky Daye", "Roll Some Mo"),
    ],
    # Folk (99 canciones)
    "Folk": [
        ("Bob Dylan", "Blowin in the Wind"),
        ("Bob Dylan", "The Times They Are a-Changin"),
        ("Bob Dylan", "Knocking on Heaven's Door"),
        ("Bob Dylan", "Like a Rolling Stone"),
        ("Bob Dylan", "Mr Tambourine Man"),
        ("Bob Dylan", "Forever Young"),
        ("Bob Dylan", "Hurricane"),
        ("Simon and Garfunkel", "The Sound of Silence"),
        ("Simon and Garfunkel", "Mrs Robinson"),
        ("Simon and Garfunkel", "Bridge Over Troubled Water"),
        ("Simon and Garfunkel", "Scarborough Fair"),
        ("Simon and Garfunkel", "The Boxer"),
        ("Simon and Garfunkel", "El Condor Pasa"),
        ("Neil Young", "Heart of Gold"),
        ("Neil Young", "Old Man"),
        ("Neil Young", "Harvest Moon"),
        ("Neil Young", "The Needle and the Damage Done"),
        ("Neil Young", "Comes a Time"),
        ("Joni Mitchell", "Big Yellow Taxi"),
        ("Joni Mitchell", "Both Sides Now"),
        ("Joni Mitchell", "River"),
        ("Joni Mitchell", "A Case of You"),
        ("Joni Mitchell", "Help Me"),
        ("Fleet Foxes", "White Winter Hymnal"),
        ("Fleet Foxes", "Helplessness Blues"),
        ("Fleet Foxes", "Mykonos"),
        ("Fleet Foxes", "Ragged Wood"),
        ("Fleet Foxes", "Blue Ridge Mountains"),
        ("Mumford and Sons", "Little Lion Man"),
        ("Mumford and Sons", "The Cave"),
        ("Mumford and Sons", "I Will Wait"),
        ("Mumford and Sons", "After the Storm"),
        ("Mumford and Sons", "Dust Bowl Dance"),
        ("Mumford and Sons", "White Blank Page"),
        ("The Lumineers", "Ho Hey"),
        ("The Lumineers", "Stubborn Love"),
        ("The Lumineers", "Ophelia"),
        ("The Lumineers", "Sleep on the Floor"),
        ("The Lumineers", "Cleopatra"),
        ("Iron and Wine", "Naked As We Came"),
        ("Iron and Wine", "Flightless Bird"),
        ("Iron and Wine", "Trapeze Swinger"),
        ("Iron and Wine", "Boy with a Coin"),
        ("Iron and Wine", "Cinder and Smoke"),
        ("Sufjan Stevens", "Death with Dignity"),
        ("Sufjan Stevens", "Chicago"),
        ("Sufjan Stevens", "Fourth of July"),
        ("Sufjan Stevens", "Should Have Known Better"),
        ("Sufjan Stevens", "Impossible Soul"),
        ("Bright Eyes", "First Day of My Life"),
        ("Bright Eyes", "Landlocked Blues"),
        ("Bright Eyes", "Lua"),
        ("Bright Eyes", "Road to Joy"),
        ("Bright Eyes", "At the Bottom of Everything"),
        ("Jose Gonzalez", "Heartbeats"),
        ("Jose Gonzalez", "Lovestain"),
        ("Jose Gonzalez", "Crosses"),
        ("Jose Gonzalez", "Down the Line"),
        ("John Denver", "Take Me Home Country Roads"),
        ("John Denver", "Rocky Mountain High"),
        ("John Denver", "Sunshine on My Shoulders"),
        ("James Taylor", "Fire and Rain"),
        ("James Taylor", "You've Got a Friend"),
        ("James Taylor", "Sweet Baby James"),
        ("Cat Stevens", "Wild World"),
        ("Cat Stevens", "Father and Son"),
        ("Cat Stevens", "Peace Train"),
        ("Cat Stevens", "Tea for the Tillerman"),
        ("Gordon Lightfoot", "If You Could Read My Mind"),
        ("Gordon Lightfoot", "Sundown"),
        ("Gordon Lightfoot", "Wreck of the Edmund Fitzgerald"),
        ("Paul Simon", "Graceland"),
        ("Paul Simon", "50 Ways to Leave Your Lover"),
        ("Paul Simon", "Slip Slidin Away"),
        ("Laura Marling", "Rambling Man"),
        ("Laura Marling", "I Was an Eagle"),
        ("Gillian Welch", "Everything Is Free"),
        ("Gillian Welch", "Time the Revelator"),
        ("Neko Case", "This Tornado Loves You"),
        ("Neko Case", "People Got a Lotta Nerve"),
        ("Alison Krauss", "When You Say Nothing at All"),
        ("Alison Krauss", "Forget About It"),
        ("Damien Rice", "The Blower's Daughter"),
        ("Damien Rice", "Cannonball"),
        ("Damien Rice", "9 Crimes"),
        ("Glen Hansard", "Falling Slowly"),
        ("Glen Hansard", "When Your Mind's Made Up"),
        ("The Decemberists", "The Engine Driver"),
        ("The Decemberists", "16 Military Wives"),
        ("Josh Ritter", "Kathleen"),
        ("Josh Ritter", "Long Shadows"),
        ("Phosphorescent", "Song for Zula"),
        ("Phosphorescent", "Wolves"),
        ("The Tallest Man on Earth", "The Gardner"),
        ("The Tallest Man on Earth", "Love Is All"),
        ("Joanna Newsom", "Sprout and the Bean"),
        ("Joanna Newsom", "Sapokanikan"),
        ("Sufjan Stevens", "Death with Dignity"),
        ("Iron and Wine", "Such Great Heights"),
    ],
}


# ─────────────────────────────────────────────────────────────────────────────
#  HTTP helper
# ─────────────────────────────────────────────────────────────────────────────

def _get_lyrics_api(artist: str, song: str, delay: float = 1.5) -> Optional[str]:
    """
    Obtiene letra desde Lyrics.ovh con rate limiting y manejo de errores.
    Espera 1.5s base + jitter aleatorio entre cada request.
    """
    url = f"{API_BASE}/{requests.utils.quote(artist)}/{requests.utils.quote(song)}"
    time.sleep(delay + random.uniform(0.2, 0.8))

    try:
        resp = requests.get(url, headers=HEADERS, timeout=10)

        if resp.status_code == 200:
            lyrics = resp.json().get("lyrics", "").strip()
            return lyrics if len(lyrics) > 50 else None
        elif resp.status_code == 404:
            log.debug("No encontrada: %s - %s", artist, song)
            return None
        elif resp.status_code == 429:
            log.warning("Rate limit. Esperando 20s...")
            time.sleep(20)
            return None
        else:
            log.warning("HTTP %s para %s - %s", resp.status_code, artist, song)
            return None

    except requests.RequestException as e:
        log.error("Error de red: %s", e)
        return None


# ─────────────────────────────────────────────────────────────────────────────
#  Pipeline principal
# ─────────────────────────────────────────────────────────────────────────────

def scrape_lyrics_ovh(
    songs_by_genre: dict[str, list[tuple[str, str]]] = None,
    max_per_genre:  int = 30,
    max_total:      int = 1000,
    existing_df:    Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """
    Descarga letras desde Lyrics.ovh y devuelve un DataFrame
    compatible con el corpus del Proyecto 1.

    Parameters
    ----------
    songs_by_genre : catalogo de canciones por genero (default: SONGS_BY_GENRE)
    max_per_genre  : maximo de canciones exitosas por genero
    max_total      : maximo total de canciones a descargar
    existing_df    : corpus existente para evitar duplicados
    """
    if songs_by_genre is None:
        songs_by_genre = SONGS_BY_GENRE

    existing_titles: set[str] = set()
    if existing_df is not None and not existing_df.empty:
        existing_titles = set(existing_df["Song"].str.lower().tolist())
        log.info("Corpus existente: %d canciones.", len(existing_titles))

    records = []
    total   = 0

    for genre, songs in songs_by_genre.items():
        if total >= max_total:
            break

        log.info("=== Genero: %s (%d canciones disponibles) ===", genre, len(songs))
        genero_count = 0

        for artist, song in songs:
            if total >= max_total or genero_count >= max_per_genre:
                break
            if song.lower() in existing_titles:
                continue

            lyrics = _get_lyrics_api(artist, song)
            if lyrics is None:
                continue

            records.append({
                "Song":      song,
                "Song year": None,
                "Artist":    artist,
                "Genre":     genre,
                "Lyrics":    lyrics,
                "Source":    "lyrics_ovh_api",
                "URL":       f"{API_BASE}/{artist}/{song}",
            })
            existing_titles.add(song.lower())
            total        += 1
            genero_count += 1
            log.info("  [%d/%d] %s - %s", total, max_total, artist, song)

        log.info("  -> %d canciones de %s", genero_count, genre)

    df = pd.DataFrame(records)
    log.info("Descarga finalizada: %d canciones nuevas.", len(df))
    return df


if __name__ == "__main__":
    print("Catalogo de canciones:")
    for g, s in SONGS_BY_GENRE.items():
        print(f"  {g:<15} {len(s):>4} canciones")
    total = sum(len(v) for v in SONGS_BY_GENRE.values())
    print(f"  {'TOTAL':<15} {total:>4} canciones")
